### ISSUE TITLE
Thanks. gpt2 or code gpt

### ISSUE THREAD

**Issue by shaileshj2803** [rifatarefin/semantic-code-search#1]
I am trying to explore more in this domain. Is this model trained on gpt2 or codegpt? Could you please send the link to the model please?

**Comment by rifatarefin** [comment]
Thanks for reaching out! The model is trained on CodeGPT. Please refer to `src/encoders/gpt2_encoder.py` file on line 39:
```
model = TFGPT2Model.from_pretrained('microsoft/CodeGPT-small-py', cache_dir = './cache/')
```

You may change this line to this to train on plain GPT-2
```
model = TFGPT2Model.from_pretrained('gpt2', cache_dir = './cache/')
```
Also, you have to change the tokenizer accordingly, please change `src/encoders/seq_encoder.py` on line 44:
```
SeqEncoder.tokenizer = GPT2TokenizerFast.from_pretrained('gpt2', cache_dir = './cache/', pad_token="<|endoftext|>", add_prefix_space=True)
```
Let me know if it helps!

**Comment by shaileshj2803** [comment]
How are the results? If you don't mind sharing. Thanks a for sharing. If you can share some evaluation data that would be very very helpful.

Thanks

**Comment by rifatarefin** [comment]
Please have a look at the [wandb log](https://wandb.ai/rifatarefin/CodeSearchNet/runs/2frlzhjy/overview?workspace=user-rifatarefin) for results on python data and [here](https://wandb.ai/rifatarefin/CodeSearchNet/runs/1nua0ifr/overview?workspace=user-rifatarefin) on Java dataset.

**Comment by shaileshj2803** [comment]
If i read it correctly the mrr is way below the previous in the paper!

**Comment by rifatarefin** [comment]
Actually yes. The GPT-2 architecture has not been able to perform well like a bi-directional transformer as BERT. This unidirectional architecture is not that great as an encoder and following the experiments, we realized this architecture is not suitable for this problem.

**Comment by shaileshj2803** [comment]
Got it. Thanks. I am trying out with codet5 with contrastive learning.

**Comment by rifatarefin** [comment]
Sounds cool! Looks like T5 has not been used for this task. However, I don't think the code for contrastive pre-training is available [https://paperswithcode.com/sota/code-search-on-codesearchnet](https://paperswithcode.com/sota/code-search-on-codesearchnet)

**Comment by shaileshj2803** [comment]
Writing my own with codet5 not using  cpt
